/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author SISTEMAS
 */
public class FrmMenuPrincipalRH extends javax.swing.JFrame {

    FrmEmpleados frmpersonal;
    FrmContratosLaborales frmcontratoslaborales;
    FrmProyectos frmcontratos;
    FrmCargos frmcargos;
    FrmResponsabilidades frmresponsabilidades;
    FrmPersonalActivo frmpersonalactivo;
    FrmPersonalRetirado frmpersonalretirado;
    
    
    public FrmMenuPrincipalRH() {
        initComponents();
        
        setTitle("Base de Datos Sistemas Consultel");

        this.getContentPane().setBackground(Color.GRAY);
        
        


        

        
        
        frmpersonal = new FrmEmpleados();
        frmcontratoslaborales = new FrmContratosLaborales();
        frmcontratos = new FrmProyectos();
        frmcargos = new FrmCargos();
        frmresponsabilidades = new FrmResponsabilidades();
        frmpersonalactivo = new FrmPersonalActivo();
        frmpersonalretirado = new FrmPersonalRetirado();
        

        
    }
    
   
    @Override
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/ConsultelLogoIcono.jpg"));
        return retValue;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        JDes_Menu = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        Lbl_NomUsuarioConectado = new javax.swing.JLabel();
        MenuBarPrincipal = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        JMI_InicioMenu = new javax.swing.JMenuItem();
        JMI_CerrarSesion = new javax.swing.JMenuItem();
        JMI_SalirMenu = new javax.swing.JMenuItem();
        MenuPersonal = new javax.swing.JMenu();
        JMI_Empleados = new javax.swing.JMenuItem();
        JMI_ContratosLaborales1 = new javax.swing.JMenuItem();
        JMI_Cargos = new javax.swing.JMenuItem();
        JMI_Responsabilidades = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuContratosLaborales = new javax.swing.JMenu();
        MenuCertificados = new javax.swing.JMenu();
        JMI_CertificadoEmpleadoActivo = new javax.swing.JMenuItem();
        JMI_CertificadoEmpleadoRetirado = new javax.swing.JMenuItem();
        MenuSedes = new javax.swing.JMenu();
        JMI_Proyectos = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        javax.swing.GroupLayout JDes_MenuLayout = new javax.swing.GroupLayout(JDes_Menu);
        JDes_Menu.setLayout(JDes_MenuLayout);
        JDes_MenuLayout.setHorizontalGroup(
            JDes_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1284, Short.MAX_VALUE)
        );
        JDes_MenuLayout.setVerticalGroup(
            JDes_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jLabel1.setText("Usuario Conectado:");

        MenuBarPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        MenuBarPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        MenuInicio.setText("Archivo");

        JMI_InicioMenu.setText("Inicio");
        JMI_InicioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_InicioMenuActionPerformed(evt);
            }
        });
        MenuInicio.add(JMI_InicioMenu);

        JMI_CerrarSesion.setText("Cerrar Sesion");
        JMI_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CerrarSesionActionPerformed(evt);
            }
        });
        MenuInicio.add(JMI_CerrarSesion);

        JMI_SalirMenu.setText("Salir");
        MenuInicio.add(JMI_SalirMenu);

        MenuBarPrincipal.add(MenuInicio);

        MenuPersonal.setText("Personal");
        MenuPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPersonalMouseClicked(evt);
            }
        });
        MenuPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPersonalActionPerformed(evt);
            }
        });

        JMI_Empleados.setText("Empleados");
        JMI_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_EmpleadosActionPerformed(evt);
            }
        });
        MenuPersonal.add(JMI_Empleados);

        JMI_ContratosLaborales1.setText("Contratos Laborales");
        JMI_ContratosLaborales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ContratosLaborales1ActionPerformed(evt);
            }
        });
        MenuPersonal.add(JMI_ContratosLaborales1);

        JMI_Cargos.setText("Cargos");
        JMI_Cargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CargosActionPerformed(evt);
            }
        });
        MenuPersonal.add(JMI_Cargos);

        JMI_Responsabilidades.setText("Responsabilidades");
        JMI_Responsabilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ResponsabilidadesActionPerformed(evt);
            }
        });
        MenuPersonal.add(JMI_Responsabilidades);

        jMenu1.setText("jMenu1");
        MenuPersonal.add(jMenu1);

        MenuBarPrincipal.add(MenuPersonal);

        MenuContratosLaborales.setText("Contratos Laborales");
        MenuContratosLaborales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContratosLaboralesActionPerformed(evt);
            }
        });
        MenuBarPrincipal.add(MenuContratosLaborales);

        MenuCertificados.setText("Certificados");
        MenuCertificados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCertificadosMouseClicked(evt);
            }
        });

        JMI_CertificadoEmpleadoActivo.setText("Personal Activo");
        JMI_CertificadoEmpleadoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CertificadoEmpleadoActivoActionPerformed(evt);
            }
        });
        MenuCertificados.add(JMI_CertificadoEmpleadoActivo);

        JMI_CertificadoEmpleadoRetirado.setText("Personal Retirado");
        JMI_CertificadoEmpleadoRetirado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CertificadoEmpleadoRetiradoActionPerformed(evt);
            }
        });
        MenuCertificados.add(JMI_CertificadoEmpleadoRetirado);

        MenuBarPrincipal.add(MenuCertificados);

        MenuSedes.setText("Sedes");
        MenuSedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSedesMouseClicked(evt);
            }
        });

        JMI_Proyectos.setText("Proyectos");
        JMI_Proyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ProyectosActionPerformed(evt);
            }
        });
        MenuSedes.add(JMI_Proyectos);

        MenuBarPrincipal.add(MenuSedes);

        MenuSalir.setText("Salir");
        MenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSalirMouseClicked(evt);
            }
        });
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        MenuBarPrincipal.add(MenuSalir);

        setJMenuBar(MenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(Lbl_NomUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JDes_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JDes_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_NomUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPersonalActionPerformed
               
    }//GEN-LAST:event_MenuPersonalActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void MenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSalirMouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_MenuSalirMouseClicked

    private void MenuPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPersonalMouseClicked
               
    }//GEN-LAST:event_MenuPersonalMouseClicked

    private void MenuCertificadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCertificadosMouseClicked
     
    }//GEN-LAST:event_MenuCertificadosMouseClicked

    private void MenuSedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSedesMouseClicked
      
    }//GEN-LAST:event_MenuSedesMouseClicked

    private void JMI_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CerrarSesionActionPerformed
        
        FrmLogin login= new FrmLogin();
        login.setVisible(true);
        login.pack();
        this.setVisible(false);
        
        
    }//GEN-LAST:event_JMI_CerrarSesionActionPerformed

    private void JMI_InicioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_InicioMenuActionPerformed
       
            frmpersonal.dispose();
                        
            frmcontratos.dispose();

    }//GEN-LAST:event_JMI_InicioMenuActionPerformed

    private void JMI_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_EmpleadosActionPerformed
          
        JDes_Menu.add(frmpersonal);

        frmpersonal.show();
        
        
    }//GEN-LAST:event_JMI_EmpleadosActionPerformed

    private void JMI_ContratosLaborales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ContratosLaborales1ActionPerformed
      
        JDes_Menu.add(frmcontratoslaborales);
        
        frmcontratoslaborales.show();
        
    }//GEN-LAST:event_JMI_ContratosLaborales1ActionPerformed

    private void JMI_CargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CargosActionPerformed
        
        
        JDes_Menu.add(frmcargos);
        
        frmcargos.show();
        
    }//GEN-LAST:event_JMI_CargosActionPerformed

    private void JMI_ResponsabilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ResponsabilidadesActionPerformed
        
        JDes_Menu.add(frmresponsabilidades);
        
        frmresponsabilidades.show();
    }//GEN-LAST:event_JMI_ResponsabilidadesActionPerformed

    private void JMI_CertificadoEmpleadoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CertificadoEmpleadoActivoActionPerformed
        
        JDes_Menu.add(frmpersonalactivo);
        
        frmpersonalactivo.show();
        
        
    }//GEN-LAST:event_JMI_CertificadoEmpleadoActivoActionPerformed

    private void JMI_CertificadoEmpleadoRetiradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CertificadoEmpleadoRetiradoActionPerformed

        JDes_Menu.add(frmpersonalretirado);
        
        frmpersonalretirado.show();
        
    }//GEN-LAST:event_JMI_CertificadoEmpleadoRetiradoActionPerformed

    private void JMI_ProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ProyectosActionPerformed
        JDes_Menu.add(frmcontratos);

        frmcontratos.show();
    }//GEN-LAST:event_JMI_ProyectosActionPerformed

    private void MenuContratosLaboralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContratosLaboralesActionPerformed
        JDes_Menu.add(frmcontratoslaborales);
        
        frmcontratoslaborales.show();
    }//GEN-LAST:event_MenuContratosLaboralesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipalRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipalRH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDes_Menu;
    private javax.swing.JMenuItem JMI_Cargos;
    private javax.swing.JMenuItem JMI_CerrarSesion;
    private javax.swing.JMenuItem JMI_CertificadoEmpleadoActivo;
    private javax.swing.JMenuItem JMI_CertificadoEmpleadoRetirado;
    private javax.swing.JMenuItem JMI_ContratosLaborales1;
    private javax.swing.JMenuItem JMI_Empleados;
    private javax.swing.JMenuItem JMI_InicioMenu;
    private javax.swing.JMenuItem JMI_Proyectos;
    private javax.swing.JMenuItem JMI_Responsabilidades;
    private javax.swing.JMenuItem JMI_SalirMenu;
    public static javax.swing.JLabel Lbl_NomUsuarioConectado;
    private javax.swing.JMenuBar MenuBarPrincipal;
    private javax.swing.JMenu MenuCertificados;
    private javax.swing.JMenu MenuContratosLaborales;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JMenu MenuPersonal;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenu MenuSedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
