/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Conexion.Conectar;
import classDAO.ContratosLaboralesDAO;
import classDAO.EmpleadosDAO;
import classVO.ContratosLaboralesVO;
import classVO.EmpleadosVO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author SISTEMAS
 */
public class FrmPersonalRetirado extends javax.swing.JInternalFrame {

         PreparedStatement ps;
          Integer idempleado = 0;
         
    
    public FrmPersonalRetirado() {
        initComponents();
    
       
        Txt_CedulaPersonalRetirado.setFocusable(true);
        Txt_CedulaPersonalRetirado.requestFocus();
        
        this.setTitle("Certificados laborales personal Retirado");

        
       
        bloquear();
        mostrarcontratoslaborales();

    }
    
    
    
 private void mostrarcontratoslaborales(){
   
     DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("F Ingreso");
    modelo.addColumn("F Retiro");
    modelo.addColumn("Tipo Contrato");
    modelo.addColumn("Cargo");
    modelo.addColumn("Salario");
    modelo.addColumn("Proyecto");   
    
    Tabla_PersonalRetirado.setModel(modelo);
    
    Object[]arrContratosLaborales = new Object [7];
        
           for(ContratosLaboralesVO carg: ContratosLaboralesDAO.getListContratosLaborales(idempleado)){
                 
                arrContratosLaborales[0] = carg.getId_contrato();
                arrContratosLaborales[1] = carg.getFecha_cont();
                arrContratosLaborales[2] = carg.getFecha_ret();
                arrContratosLaborales[3] = carg.getTipo_contrato();
                arrContratosLaborales[4] = carg.getCargo();
                arrContratosLaborales[5] = carg.getSalario();
                arrContratosLaborales[6] = carg.getProyecto();
                
                modelo.addRow(arrContratosLaborales);
            }
            Tabla_PersonalRetirado.setModel(modelo);
            
    }   
    

    
   void bloquear(){
       
    Txt_IdContratoPersonalRetirado.setEnabled(false);
    Txt_CedulaPersonalRetirado.setEnabled(true);
    Txt_NombrePersonalRetirado.setEnabled(false);
    Txt_ObservacionPersonalRetirado.setEnabled(true);
    
    Btn_ConsultarPersonalRetirado.setEnabled(true);
    
    } 
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Lbl_NombreCompletoContrato = new javax.swing.JLabel();
        Txt_CedulaPersonalRetirado = new javax.swing.JTextField();
        Lbl_IdContrato = new javax.swing.JLabel();
        Txt_IdContratoPersonalRetirado = new javax.swing.JTextField();
        Lbl_ObservacionContrato = new javax.swing.JLabel();
        Txt_ObservacionPersonalRetirado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_PersonalRetirado = new javax.swing.JTable();
        Lbl_CedulaEmpleadoRetirado = new javax.swing.JLabel();
        Txt_NombrePersonalRetirado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Btn_ConsultarPersonalRetirado = new javax.swing.JButton();
        Btn_LimpiarPersonalRetirado = new javax.swing.JButton();
        Btn_CertificadoSinFunciones = new javax.swing.JButton();
        Btn_CertificadoConFunciones = new javax.swing.JButton();
        Btn_SalirPersonalRetirado = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Lbl_NombreCompletoContrato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_NombreCompletoContrato.setText("Nombre Completo");

        Txt_CedulaPersonalRetirado.setBackground(new java.awt.Color(255, 255, 255));
        Txt_CedulaPersonalRetirado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_IdContrato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_IdContrato.setText("Id Contrato");

        Txt_IdContratoPersonalRetirado.setEditable(false);
        Txt_IdContratoPersonalRetirado.setBackground(new java.awt.Color(255, 255, 255));
        Txt_IdContratoPersonalRetirado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_ObservacionContrato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_ObservacionContrato.setText("Observacion");

        Txt_ObservacionPersonalRetirado.setBackground(new java.awt.Color(255, 255, 255));
        Txt_ObservacionPersonalRetirado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla_PersonalRetirado.setBackground(new java.awt.Color(255, 255, 255));
        Tabla_PersonalRetirado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tabla_PersonalRetirado.setForeground(new java.awt.Color(0, 0, 0));
        Tabla_PersonalRetirado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "F Ingreso", "F Retiro", "Tipo Contrato", "Cargo", "Salario", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_PersonalRetirado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_PersonalRetiradoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_PersonalRetirado);
        if (Tabla_PersonalRetirado.getColumnModel().getColumnCount() > 0) {
            Tabla_PersonalRetirado.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        Lbl_CedulaEmpleadoRetirado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_CedulaEmpleadoRetirado.setText("Cedula");

        Txt_NombrePersonalRetirado.setBackground(new java.awt.Color(255, 255, 255));
        Txt_NombrePersonalRetirado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Txt_NombrePersonalRetirado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Btn_ConsultarPersonalRetirado.setBackground(new java.awt.Color(0, 0, 0));
        Btn_ConsultarPersonalRetirado.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ConsultarPersonalRetirado.setText("Buscar");
        Btn_ConsultarPersonalRetirado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConsultarPersonalRetiradoActionPerformed(evt);
            }
        });

        Btn_LimpiarPersonalRetirado.setBackground(new java.awt.Color(0, 0, 0));
        Btn_LimpiarPersonalRetirado.setForeground(new java.awt.Color(255, 255, 255));
        Btn_LimpiarPersonalRetirado.setText("Limpiar");
        Btn_LimpiarPersonalRetirado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarPersonalRetiradoActionPerformed(evt);
            }
        });

        Btn_CertificadoSinFunciones.setBackground(new java.awt.Color(0, 0, 0));
        Btn_CertificadoSinFunciones.setForeground(new java.awt.Color(255, 255, 255));
        Btn_CertificadoSinFunciones.setText("Retirados Sin Funciones");
        Btn_CertificadoSinFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CertificadoSinFuncionesActionPerformed(evt);
            }
        });

        Btn_CertificadoConFunciones.setBackground(new java.awt.Color(0, 0, 0));
        Btn_CertificadoConFunciones.setForeground(new java.awt.Color(255, 255, 255));
        Btn_CertificadoConFunciones.setText("Retirados con Funciones");
        Btn_CertificadoConFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CertificadoConFuncionesActionPerformed(evt);
            }
        });

        Btn_SalirPersonalRetirado.setBackground(new java.awt.Color(0, 0, 0));
        Btn_SalirPersonalRetirado.setForeground(new java.awt.Color(255, 255, 255));
        Btn_SalirPersonalRetirado.setText("Salir");
        Btn_SalirPersonalRetirado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirPersonalRetiradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_ConsultarPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Btn_LimpiarPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_CertificadoSinFunciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_CertificadoConFunciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_SalirPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_ConsultarPersonalRetirado)
                    .addComponent(Btn_LimpiarPersonalRetirado)
                    .addComponent(Btn_CertificadoSinFunciones)
                    .addComponent(Btn_CertificadoConFunciones)
                    .addComponent(Btn_SalirPersonalRetirado))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_ObservacionPersonalRetirado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Txt_IdContratoPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(Txt_CedulaPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_IdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(Lbl_CedulaEmpleadoRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Lbl_ObservacionContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_NombreCompletoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_NombrePersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_IdContrato)
                    .addComponent(Lbl_CedulaEmpleadoRetirado)
                    .addComponent(Lbl_NombreCompletoContrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_IdContratoPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_CedulaPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_NombrePersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_ObservacionContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_ObservacionPersonalRetirado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla_PersonalRetiradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_PersonalRetiradoMouseClicked

        int fila= Tabla_PersonalRetirado.getSelectedRow();
        
        if(fila>=0){
            Txt_IdContratoPersonalRetirado.setText(Tabla_PersonalRetirado.getValueAt(fila, 0).toString());
   
        }
        else{
            JOptionPane.showMessageDialog(null,"no seleciono fila");
        }
          
    }//GEN-LAST:event_Tabla_PersonalRetiradoMouseClicked

    private void Btn_ConsultarPersonalRetiradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConsultarPersonalRetiradoActionPerformed
     
        
        EmpleadosVO empl = EmpleadosDAO.buscarEmpleado(Txt_CedulaPersonalRetirado.getText());
        idempleado = (empl.getId_empleado());
        Txt_NombrePersonalRetirado.setText(empl.getNombre()+ " " + (empl.getApellidos()));

        mostrarcontratoslaborales();
        
        int fila = Tabla_PersonalRetirado.getRowCount () - 1;
    
            Txt_IdContratoPersonalRetirado.setText(Tabla_PersonalRetirado.getValueAt(fila, 0).toString());
        
    }//GEN-LAST:event_Btn_ConsultarPersonalRetiradoActionPerformed

    private void Btn_LimpiarPersonalRetiradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarPersonalRetiradoActionPerformed
        
        Limpiar();
        bloquear();
    }//GEN-LAST:event_Btn_LimpiarPersonalRetiradoActionPerformed

    private void Btn_SalirPersonalRetiradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirPersonalRetiradoActionPerformed

        Limpiar();
        dispose();
 
    }//GEN-LAST:event_Btn_SalirPersonalRetiradoActionPerformed

    private void Btn_CertificadoSinFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CertificadoSinFuncionesActionPerformed
        
        try {

         Conectar con = new Conectar();
     //INVOCAMOS AL METODO CONEXION
         Connection cn = con.Conectar();
            
            JasperReport reporte = null;
            String path = "src\\Reportes\\CertificadoRetiradosSinFunciones.jasper";

            Map parametro = new HashMap();
            parametro.put("Id_Contrato",Txt_IdContratoPersonalRetirado.getText());
            parametro.put("Nombre_Apellidos",Txt_NombrePersonalRetirado.getText());
            parametro.put("Cedula",Txt_CedulaPersonalRetirado.getText());
//            parametro.put("Cargo",Txt_CargoContrato.getText());
            parametro.put("FirmaPrincipal",2);
                        
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);

            JasperViewer view = new JasperViewer(jprint, false);             

            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(FrmPersonalRetirado.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_CertificadoSinFuncionesActionPerformed

    private void Btn_CertificadoConFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CertificadoConFuncionesActionPerformed
      
        try {

         Conectar con = new Conectar();
     //INVOCAMOS AL METODO CONEXION
         Connection cn = con.Conectar();
            
            JasperReport reporte = null;
            String path = "src\\Reportes\\CertificadoRetiradosConFunciones.jasper";

            Map parametro = new HashMap();
            parametro.put("Id_Contrato",Txt_IdContratoPersonalRetirado.getText());
            parametro.put("Nombre_Apellidos",Txt_NombrePersonalRetirado.getText());
            parametro.put("Cedula",Txt_CedulaPersonalRetirado.getText());
//            parametro.put("Cargo",Txt_CargoContrato.getText());
            parametro.put("FirmaPrincipal",2);
                        
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);

            JasperViewer view = new JasperViewer(jprint, false);             

            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(FrmPersonalRetirado.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
    }//GEN-LAST:event_Btn_CertificadoConFuncionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CertificadoConFunciones;
    private javax.swing.JButton Btn_CertificadoSinFunciones;
    private javax.swing.JButton Btn_ConsultarPersonalRetirado;
    private javax.swing.JButton Btn_LimpiarPersonalRetirado;
    private javax.swing.JButton Btn_SalirPersonalRetirado;
    private javax.swing.JLabel Lbl_CedulaEmpleadoRetirado;
    private javax.swing.JLabel Lbl_IdContrato;
    private javax.swing.JLabel Lbl_NombreCompletoContrato;
    private javax.swing.JLabel Lbl_ObservacionContrato;
    private javax.swing.JTable Tabla_PersonalRetirado;
    private javax.swing.JTextField Txt_CedulaPersonalRetirado;
    private javax.swing.JTextField Txt_IdContratoPersonalRetirado;
    private javax.swing.JTextField Txt_NombrePersonalRetirado;
    private javax.swing.JTextField Txt_ObservacionPersonalRetirado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

     Conectar con = new Conectar();
     //INVOCAMOS AL METODO CONEXION
     Connection cn = con.Conectar();
     

     
 private void Limpiar(){
     
        Txt_IdContratoPersonalRetirado.setText("");
        Txt_CedulaPersonalRetirado.setText("");
        Txt_NombrePersonalRetirado.setText("");
        Txt_IdContratoPersonalRetirado.setText("");
        Txt_ObservacionPersonalRetirado.setText("");
                
        Btn_ConsultarPersonalRetirado.setEnabled(true);
        
        idempleado=0;
        mostrarcontratoslaborales();
        
     }     

 
}

