/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Conexion.Conectar;
import classDAO.ContratosLaboralesDAO;
import classDAO.EmpleadosDAO;
import classVO.ContratosLaboralesVO;
import classVO.EmpleadosVO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author SISTEMAS
 */
public class FrmPersonalActivo extends javax.swing.JInternalFrame {

         PreparedStatement ps;
          Integer idempleado = 0;
         
    
    public FrmPersonalActivo() {
        initComponents();
    
       
        Txt_CedulaPersonalActivo.setFocusable(true);
        Txt_CedulaPersonalActivo.requestFocus();
        
        this.setTitle("Certificados laborales personal Activo");

       
        bloquear();
        mostrarcontratoslaborales();

    }
    
    
    
 private void mostrarcontratoslaborales(){
   
     DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("F Ingreso");
    modelo.addColumn("F Retiro");
    modelo.addColumn("Tipo Contrato");
    modelo.addColumn("Cargo");
    modelo.addColumn("Salario");
    modelo.addColumn("Proyecto");   
    
    Tabla_PersonalActivo.setModel(modelo);
    
    Object[]arrContratosLaborales = new Object [7];
        
           for(ContratosLaboralesVO carg: ContratosLaboralesDAO.getListContratosLaborales(idempleado)){
                 
                arrContratosLaborales[0] = carg.getId_contrato();
                arrContratosLaborales[1] = carg.getFecha_cont();
                arrContratosLaborales[2] = carg.getFecha_ret();
                arrContratosLaborales[3] = carg.getTipo_contrato();
                arrContratosLaborales[4] = carg.getCargo();
                arrContratosLaborales[5] = carg.getSalario();
                arrContratosLaborales[6] = carg.getProyecto();
                
                modelo.addRow(arrContratosLaborales);
            }
            Tabla_PersonalActivo.setModel(modelo);
            
    }   
    

    
   void bloquear(){
       
    Txt_IdContratoPersonalActivo.setEnabled(false);
    Txt_CedulaPersonalActivo.setEnabled(true);
    Txt_NombrePersonalActivo.setEnabled(false);
    Txt_ObservacionPersonalActivo.setEnabled(true);
    
    Btn_BuscarPersonalActivo.setEnabled(true);
    
    } 
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Lbl_NombreCompletoContrato = new javax.swing.JLabel();
        Txt_CedulaPersonalActivo = new javax.swing.JTextField();
        Lbl_IdContrato = new javax.swing.JLabel();
        Txt_IdContratoPersonalActivo = new javax.swing.JTextField();
        Lbl_ObservacionContrato = new javax.swing.JLabel();
        Txt_ObservacionPersonalActivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_PersonalActivo = new javax.swing.JTable();
        Lbl_CedulaContrato = new javax.swing.JLabel();
        Txt_NombrePersonalActivo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Btn_BuscarPersonalActivo = new javax.swing.JButton();
        Btn_LimpiarContrato = new javax.swing.JButton();
        Btn_CertificadoSinFunciones = new javax.swing.JButton();
        Btn_CertificadoConFunciones = new javax.swing.JButton();
        Btn_SalirContrato1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Lbl_NombreCompletoContrato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_NombreCompletoContrato.setText("Nombre Completo");

        Txt_CedulaPersonalActivo.setBackground(new java.awt.Color(255, 255, 255));
        Txt_CedulaPersonalActivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_IdContrato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_IdContrato.setText("Id Contrato");

        Txt_IdContratoPersonalActivo.setEditable(false);
        Txt_IdContratoPersonalActivo.setBackground(new java.awt.Color(255, 255, 255));

        Lbl_ObservacionContrato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_ObservacionContrato.setText("Observacion");

        Txt_ObservacionPersonalActivo.setBackground(new java.awt.Color(255, 255, 255));
        Txt_ObservacionPersonalActivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla_PersonalActivo.setBackground(new java.awt.Color(255, 255, 255));
        Tabla_PersonalActivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tabla_PersonalActivo.setForeground(new java.awt.Color(0, 0, 0));
        Tabla_PersonalActivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "F Ingreso", "F Retiro", "Tipo Contrato", "Cargo", "Salario", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_PersonalActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_PersonalActivoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_PersonalActivo);
        if (Tabla_PersonalActivo.getColumnModel().getColumnCount() > 0) {
            Tabla_PersonalActivo.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        Lbl_CedulaContrato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_CedulaContrato.setText("Cedula");

        Txt_NombrePersonalActivo.setBackground(new java.awt.Color(255, 255, 255));
        Txt_NombrePersonalActivo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Txt_NombrePersonalActivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Btn_BuscarPersonalActivo.setBackground(new java.awt.Color(0, 0, 0));
        Btn_BuscarPersonalActivo.setForeground(new java.awt.Color(255, 255, 255));
        Btn_BuscarPersonalActivo.setText("Buscar");
        Btn_BuscarPersonalActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarPersonalActivoActionPerformed(evt);
            }
        });

        Btn_LimpiarContrato.setBackground(new java.awt.Color(0, 0, 0));
        Btn_LimpiarContrato.setForeground(new java.awt.Color(255, 255, 255));
        Btn_LimpiarContrato.setText("Limpiar");
        Btn_LimpiarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarContratoActionPerformed(evt);
            }
        });

        Btn_CertificadoSinFunciones.setBackground(new java.awt.Color(0, 0, 0));
        Btn_CertificadoSinFunciones.setForeground(new java.awt.Color(255, 255, 255));
        Btn_CertificadoSinFunciones.setText("Activos Sin Funciones");
        Btn_CertificadoSinFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CertificadoSinFuncionesActionPerformed(evt);
            }
        });

        Btn_CertificadoConFunciones.setBackground(new java.awt.Color(0, 0, 0));
        Btn_CertificadoConFunciones.setForeground(new java.awt.Color(255, 255, 255));
        Btn_CertificadoConFunciones.setText("Activos con Funciones");
        Btn_CertificadoConFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CertificadoConFuncionesActionPerformed(evt);
            }
        });

        Btn_SalirContrato1.setBackground(new java.awt.Color(0, 0, 0));
        Btn_SalirContrato1.setForeground(new java.awt.Color(255, 255, 255));
        Btn_SalirContrato1.setText("Salir");
        Btn_SalirContrato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirContrato1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_BuscarPersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_LimpiarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_CertificadoSinFunciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_CertificadoConFunciones)
                .addGap(18, 18, 18)
                .addComponent(Btn_SalirContrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_BuscarPersonalActivo)
                    .addComponent(Btn_LimpiarContrato)
                    .addComponent(Btn_CertificadoSinFunciones)
                    .addComponent(Btn_CertificadoConFunciones)
                    .addComponent(Btn_SalirContrato1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_IdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_IdContratoPersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_CedulaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(224, 224, 224)
                                        .addComponent(Lbl_NombreCompletoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Txt_CedulaPersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Txt_NombrePersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(Lbl_ObservacionContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Txt_ObservacionPersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_IdContrato)
                    .addComponent(Lbl_CedulaContrato)
                    .addComponent(Lbl_NombreCompletoContrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_IdContratoPersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_CedulaPersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_NombrePersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_ObservacionContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_ObservacionPersonalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla_PersonalActivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_PersonalActivoMouseClicked

        int fila= Tabla_PersonalActivo.getSelectedRow();
        
        if(fila>=0){
            Txt_IdContratoPersonalActivo.setText(Tabla_PersonalActivo.getValueAt(fila, 0).toString());
   
        }
        else{
            JOptionPane.showMessageDialog(null,"no seleciono fila");
        }
          
    }//GEN-LAST:event_Tabla_PersonalActivoMouseClicked

    private void Btn_BuscarPersonalActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarPersonalActivoActionPerformed
     
        
        EmpleadosVO empl = EmpleadosDAO.buscarEmpleado(Txt_CedulaPersonalActivo.getText());
        idempleado = (empl.getId_empleado());
        Txt_NombrePersonalActivo.setText(empl.getNombre()+ " " + (empl.getApellidos()));

        mostrarcontratoslaborales();
        
        int fila = Tabla_PersonalActivo.getRowCount () - 1;
    
            Txt_IdContratoPersonalActivo.setText(Tabla_PersonalActivo.getValueAt(fila, 0).toString());
        
    }//GEN-LAST:event_Btn_BuscarPersonalActivoActionPerformed

    private void Btn_LimpiarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarContratoActionPerformed
        
        Limpiar();
        bloquear();
    }//GEN-LAST:event_Btn_LimpiarContratoActionPerformed

    private void Btn_SalirContrato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirContrato1ActionPerformed

        Limpiar();
        dispose();
 
    }//GEN-LAST:event_Btn_SalirContrato1ActionPerformed

    private void Btn_CertificadoSinFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CertificadoSinFuncionesActionPerformed
        
        try {

         Conectar con = new Conectar();
     //INVOCAMOS AL METODO CONEXION
         Connection cn = con.Conectar();
            
            JasperReport reporte = null;
            String path = "src\\Reportes\\CertificadoActivosSinFunciones.jasper";

            Map parametro = new HashMap();
            parametro.put("Id_Contrato",Txt_IdContratoPersonalActivo.getText());
            parametro.put("Nombre_Apellidos",Txt_NombrePersonalActivo.getText());
            parametro.put("Cedula",Txt_CedulaPersonalActivo.getText());
//            parametro.put("Cargo",Txt_CargoContrato.getText());
            parametro.put("FirmaPrincipal",2);
                        
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);

            JasperViewer view = new JasperViewer(jprint, false);             

            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(FrmPersonalActivo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_CertificadoSinFuncionesActionPerformed

    private void Btn_CertificadoConFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CertificadoConFuncionesActionPerformed
      
        try {

         Conectar con = new Conectar();
     //INVOCAMOS AL METODO CONEXION
         Connection cn = con.Conectar();
            
            JasperReport reporte = null;
            String path = "src\\Reportes\\CertificadoActivosConFunciones.jasper";

            Map parametro = new HashMap();
            parametro.put("Id_Contrato",Txt_IdContratoPersonalActivo.getText());
            parametro.put("Nombre_Apellidos",Txt_NombrePersonalActivo.getText());
            parametro.put("Cedula",Txt_CedulaPersonalActivo.getText());
//            parametro.put("Cargo",Txt_CargoContrato.getText());
            parametro.put("FirmaPrincipal",2);
                        
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);

            JasperViewer view = new JasperViewer(jprint, false);             

            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(FrmPersonalActivo.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
    }//GEN-LAST:event_Btn_CertificadoConFuncionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BuscarPersonalActivo;
    private javax.swing.JButton Btn_CertificadoConFunciones;
    private javax.swing.JButton Btn_CertificadoSinFunciones;
    private javax.swing.JButton Btn_LimpiarContrato;
    private javax.swing.JButton Btn_SalirContrato1;
    private javax.swing.JLabel Lbl_CedulaContrato;
    private javax.swing.JLabel Lbl_IdContrato;
    private javax.swing.JLabel Lbl_NombreCompletoContrato;
    private javax.swing.JLabel Lbl_ObservacionContrato;
    private javax.swing.JTable Tabla_PersonalActivo;
    private javax.swing.JTextField Txt_CedulaPersonalActivo;
    private javax.swing.JTextField Txt_IdContratoPersonalActivo;
    private javax.swing.JTextField Txt_NombrePersonalActivo;
    private javax.swing.JTextField Txt_ObservacionPersonalActivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

     Conectar con = new Conectar();
     //INVOCAMOS AL METODO CONEXION
     Connection cn = con.Conectar();
     

     
 private void Limpiar(){
     
        Txt_IdContratoPersonalActivo.setText("");
        Txt_CedulaPersonalActivo.setText("");
        Txt_NombrePersonalActivo.setText("");
        Txt_IdContratoPersonalActivo.setText("");
        Txt_ObservacionPersonalActivo.setText("");
                
        Btn_BuscarPersonalActivo.setEnabled(true);
        
        idempleado=0;
        mostrarcontratoslaborales();
        
     }     

 
}

